# Generated by Django 2.2.24 on 2022-09-14 18:20

from django.db import migrations


def identify_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building_year = 2015

    for flat in Flat.objects.all():
        if flat.construction_year >= new_building_year:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220914_1955'),
    ]

    operations = [
        migrations.RunPython(identify_new_building, ),
    ]
