# Generated by Django 2.2.24 on 2022-09-16 15:10
import phonenumbers

from django.db import migrations


def normalize_owners_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        normalization_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        international_number = phonenumbers.format_number(normalization_number, phonenumbers.PhoneNumberFormat.E164)
        if not normalization_number.italian_leading_zero:
            flat.owner_pure_phone = international_number
        else:
            flat.owner_pure_phone = ''
        flat.save()


def rollback(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_owners_phonenumber, rollback),
    ]
