# Generated by Django 2.2.24 on 2022-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220917_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owners_flat', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
