# Generated by Django 2.2.24 on 2022-09-27 11:46

from django.db import migrations


def update_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.name = owner.owner
        owner.phonenumber = owner.owner_pure_phone
        owner.save()


def rollback(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.name = None
        owner.phonenumber = None
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220927_1445'),
    ]

    operations = [
        migrations.RunPython(update_owners, rollback),
    ]
