# Generated by Django 2.2.24 on 2022-09-27 11:46

from django.db import migrations
from django.db.models import F


def update_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.update(
        name=F('owner'),
        phonenumber=F('owner_pure_phone'),
    )

def rollback(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.update(
        name=None,
        phonenumber=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220927_1445'),
    ]

    operations = [
        migrations.RunPython(update_owners, rollback),
    ]
