# Generated by Django 2.2.24 on 2022-09-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220927_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
    ]
