# Generated by Django 2.2.24 on 2022-09-28 19:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20220927_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region='RU', verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
